server:
  port: 9001
spring:
  application:
    name: myshop-user
  datasource:
    url: jdbc:mysql://192.168.186.137:3306/mysql?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root@123456
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源
  jpa:
    show-sql: true # 是否打印sql语句
    generate-ddl: true # 是否自动建表
    database: mysql # jpa连接的数据库类型
eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url: # 客户端注册地址
      defaultZone: http://localhost:8888/eureka
  instance:
    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    prefer-ip-address: true
